//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("uniq")]
[assembly: AssemblyTitle("uniq")]
[assembly: AssemblyDescription("Description of uniq.")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyCompany("Rik Cousens")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug version")]
#else
[assembly: AssemblyConfiguration("Release version")]
#endif
[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]

// default namespace

