@ECHO OFF
SETLOCAL

FOR /F %%F IN ('DIR /s/b *.CSPROJ') DO (
REM CALL MSBUILD --nologo -v:m %%F
CALL MSBUILD --nologo -v:q %%F
IF ERRORLEVEL 5 ECHO ACK-5!
IF ERRORLEVEL 4 ECHO ACK-4!
IF ERRORLEVEL 3 ECHO ACK-3!
IF ERRORLEVEL 2 ECHO ACK-2!
IF ERRORLEVEL 1 ECHO ACK-1: %%F failed to build
)
