//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("which")]
[assembly: AssemblyTitle("which")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyCompany("Phibro LLC.")]
[assembly: AssemblyDescription("description of which here.")]
[assembly: AssemblyCopyright("Copyright(c) 2007, Phibro LLC.")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug version")]
#else
[assembly: AssemblyConfiguration("Release version")]
#endif
[assembly: ComVisible(false)]


